## Analysis for CCS3

In [13]:
import pandas as pd
import numpy as np

Some basic data loading and cleanup of useless columns

In [14]:
def clean_df(df: pd.DataFrame):
    return df.drop(columns=['Recording'])

In [15]:
df = pd.concat([pd.read_csv(f'metrics{i}.tsv', sep='\t') for i in range(1,5)])
df = clean_df(df)
participants = {name: df[df['Participant']==name] for name in df['Participant'].unique()}

In [16]:
jarl = participants['Sebastian']
jarl

,Participant,TOI,Interval,Media,AOI,Last_key_press,Total_duration_of_fixations,Average_duration_of_fixations,Minimum_duration_of_fixations,Maximum_duration_of_fixations,...,Minimum_duration_of_Glances,Maximum_duration_of_Glances,Number_of_Glances,Time_to_first_Glance,Number_of_saccades_in_AOI,Character_index,Word_index,AOI_string,Regression-path_duration,Re-reading_duration
0,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",-,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,2.0,8.0,-,0.0,0.0
1,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",-,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,3.0,1.0,-,0.0,0.0
2,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,5.0,1.0,",",0.0,0.0
3,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,10.0,2.0,",",0.0,0.0
4,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,9.0,5.0,",",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8431,Sebastian,Entire Recording,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,8.0,ш,0.0,0.0
8432,Sebastian,Entire Recording,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,794,265.0,243.0,293.0,...,257.0,321.0,3,262376.0,0,1.0,1.0,ш,794.0,0.0
8433,Sebastian,Entire Recording,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,1.0,ш,0.0,0.0
8434,Sebastian,Entire Recording,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,5.0,ш,NaN,NaN
8435,Sebastian,Entire Recording,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,7.0,ш,NaN,NaN

In [ ]:
jarl.columns

## Basic Analysis

### fixation time of letters, grouped by position-group

### fixation time of each cyrillic letter, t test between first time it got fixated vs last time (to see if they learned)

### average fixation time on latin letters vs on cyrillic (to see if they actually put more effort)

### number of visits (nuumber of fixations???) to the cyrillic letters vs ???

### did they learn better the letters on start/end?
check the answers to the questions using keystrokes

In [20]:
all1, all2 = jarl['Media'].unique()[0], jarl['Media'].unique()[-1]
jarl[jarl['Media']==all1]

,Participant,TOI,Interval,Media,AOI,Last_key_press,Total_duration_of_fixations,Average_duration_of_fixations,Minimum_duration_of_fixations,Maximum_duration_of_fixations,...,Minimum_duration_of_Glances,Maximum_duration_of_Glances,Number_of_Glances,Time_to_first_Glance,Number_of_saccades_in_AOI,Character_index,Word_index,AOI_string,Regression-path_duration,Re-reading_duration
0,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",-,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,2.0,8.0,-,0.0,0.0
1,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",-,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,3.0,1.0,-,0.0,0.0
2,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,5.0,1.0,",",0.0,0.0
3,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,10.0,2.0,",",0.0,0.0
4,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",",",Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,9.0,5.0,",",0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,8.0,ш,0.0,0.0
2796,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,794,265.0,243.0,293.0,...,257.0,321.0,3,212986.0,0,1.0,1.0,ш,794.0,0.0
2797,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,1.0,ш,0.0,0.0
2798,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,5.0,ш,NaN,NaN
2799,Sebastian,TOI_stimuli,1,"b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,ch1 (1),ch2 (1)...",ш,Space,0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,1.0,7.0,ш,NaN,NaN